

# main_title: The title of the website.
main_title: "Tasso in Music Project"

# main_subtitle: The subtitle on the homepage.
main_subtitle: Digital Edition of the Settings of Torquato Tasso's Poetry, c. 1570&ndash;1640

# variorum_modified: The date that the variorum was last regenerated:
variorum_modified: 2020/07/28

# deployment: either "local" for loading javascripts from the website
# or "external" for loading from content deployment networks or other
# non-website sources.
deployment: external

# defaults: default jekyll settings.
defaults:
  -
    scope:
      path: ""
      type: "main"
    values:
      layout: "main"
  -
    scope:
      path: ""
      type: "full"
    values:
      layout: "full"


markdown: kramdown

kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

highlighter: rouge


# Google Analytics tracking number:
google_analytics: "UA-96036055-1"


### External URLs ##########################################

# data (PDFs, MP3s, etc)
tasso_data_url: "https://josquin.stanford.edu/cgi-bin/tasso"
tasso_data_url_new: "https://data.tassomusic.org"

url: "https://www.tassomusic.org"


### Data files #############################################

# worklist: list of available musical settings, prepared automatically
worklist: "/data/indexes/worklist.json"

rime_settings: "/data/indexes/rime-settings.aton"
aminta_settings: "/data/indexes/aminta-settings.aton"
gerusalemme_settings: "/data/indexes/gerusalemme-settings.aton"
other_settings: "/data/indexes/other-settings.aton"

rime_verses: "/data/indexes/rime-verses.aton"
critical_reports: "/data/reports"

literary_prints: "/data/indexes/literary-prints.aton"
literary_manuscripts: "/data/indexes/literary-manuscripts.aton"

sigla_list: "/data/support/sigla.aton"


### CSS variables ##########################################

# tab_color: light beige color for background of tabs on main page
tab_color: "#c2ab6c"

# heading_color: lightish beige for table headings, tab titles, etc.
heading_color: "#96835c"

# hyperlink color:
hyperlink_color: "#96835c"

# button color:
button_color: "#A6330c"

# button text color:
button_text_color: "#f8f8f8"

# button font:
button_font: "Helvetica"


